### PR TITLE
Fix wrong aria-roles

### PR DESCRIPTION
**Pull request by srsgores**
* Correct role="navigation"
* Add role="application"
* Add footer contentinfo role
* Use nav instead of div for nav
* Add role="banner" for main header

### CODE REVIEW

**Comment by srsgores** [comment]
This also fixes the datepicker on mobile, and allows users to use the native one in Chrome/Chrome for Android if the browser supports it.  Makes inputting dates a lot easier...

**Comment by interlock** [comment]
Thanks @srsgores  Looks good. I may check for more missed roles before we merge. Did you glance over the admin views?

**Comment by srsgores** [comment]
No, just the base layout.  My time was limited, as you can imagine.

**Comment by srsgores** [comment]
Status?

**Comment by interlock** [comment]
Been a busy few days at LHL, so just getting to two other merges today and hopefully a deploy.

**Pull request merged**
